hostname r4
log syslog informational
no ipv6 forwarding
!
router ospf
 ospf router-id 4.4.4.4
 network 10.0.24.0/29 area 0
 network 10.0.34.0/29 area 0
 network 10.0.45.0/29 area 0
 network 192.168.4.0/24 area 0
!
line vty
!
