hostname r5
log syslog informational
no ipv6 forwarding
!
router rip
 version 2
 network 10.0.15.0/29
 network 10.0.35.0/29
 network 10.0.45.0/29
 network 192.168.5.0/24
 no auto-summary
 redistribute connected
!
line vty
!
