hostname r3
log syslog informational
no ipv6 forwarding
!
router ospf
 ospf router-id 3.3.3.3
 network 10.0.23.0/29 area 0
 network 10.0.34.0/29 area 0
 network 10.0.35.0/29 area 0
 network 192.168.3.0/24 area 0
!
line vty
!
